#index:
#    path: /
#    controller: App\Controller\DefaultController::index
first:
   path: /
   controller: App\Controller\Standard::start
second:
   path: /start
   controller: App\Controller\Standard::starting
third:
   path: /zapros
   controller: App\Controller\Zapros::something
